description: PhillyTools ConfigFile for s3prl

# AML
target:
#  name: itpscusv100cl
#  name: itplabrr1cl1
#  name: itp-v100-wus2
#  name: itp-v100-scus-2
#  name: itp-v100-scus
  name: a100-scus
#  name: v100-32gb-eus-2
#  name: itpeastusv100cl
#  name: itpeastusv100cl2
#  name: itpeusp100cl
#  name: itpwus2v100cl
#  name: itpseasiav100cl
  service: amlk8s
#  vc: resrchvc
#  vc: speech-itp-am-e2e
  vc: speech-itp-adb
#  queue: bonus

# docker environment
environment:
  image: iashin/specvqgan:latest


# code dir
code:
  local_dir: .

# amlt run .\itp_scripts\spec_vqgan.yaml specvqgan_audioset_codebook_fbank_fsp_esc50_patch_onl_hubert_p4 -y
# amlt run .\itp_scripts\spec_vqgan.yaml specvqgan_audioset_codebook_fbank_t1 -y
# amlt run .\itp_scripts\spec_vqgan.yaml specvqgan_audioset_codebook_fbank -y
# amlt run .\itp_scripts\spec_vqgan.yaml specvqgan_audioset_fbank -y
# amlt run .\itp_scripts\spec_vqgan.yaml spec_vqgan_sleep -y

# job config
jobs:
  - name: training
    sku: G8
#    sku_count: 4
#    aml_mpirun:
#      process_count_per_node: 8
#      communicator: "OpenMpi"
    command:
      - bash bash_scripts/train_audioset_codebook.sh
      - sleep infinity

# azure blob configuration
storage:
  data_blob:
#    storage_account_name: tsprmblob01eus
    storage_account_name: tsprmblob01scus
#    storage_account_name: tsprmblob01wus2
    container_name: data
    mount_dir: /datablob
    mount_options:
    - -o
    - attr_timeout=240
    - -o
    - entry_timeout=240
    - -o
    - negative_timeout=120
    - -o
    - allow_other
    - --log-level=LOG_WARNING
    - --file-cache-timeout-in-seconds=360000000
  blob_model:
#    storage_account_name: tsstd01eus
    storage_account_name: tsstd01scus
#    storage_account_name: tsstd01wus2
    container_name: models
    mount_dir: /modelblob
    mount_options:
    - --file-cache-timeout-in-seconds=360000000
  myblob_data:
      storage_account_name: tsprmblob01scus
      container_name: data
      mount_dir: /datablob2
      mount_options:
      - -o
      - attr_timeout=240
      - -o
      - entry_timeout=240
      - -o
      - negative_timeout=120
      - -o
      - allow_other
      - --log-level=LOG_WARNING
      - --file-cache-timeout-in-seconds=360000000
