model:
  base_learning_rate: 4.5e-6
  target: specvqgan.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 992
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [1, 1, 2, 2, 4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [62]
      dropout: 0.0

    lossconfig:
      target: specvqgan.modules.losses.vqperceptual.VQLPAPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0
        min_adapt_weight: 1.0
        max_adapt_weight: 1.0
        perceptual_weight: 0.0

lightning:
  callbacks:
    image_logger:
      target: train.ImageLogger
      params:
        for_specs: True
        vocoder_cfg:
          target: train.VocoderMelGan
          params:
            ckpt_vocoder: './vocoder/logs/vggsound/'
  trainer:
    sync_batchnorm: true

data:
  target: train.FbankDataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4

    spec_dir_path: '/datablob/users/v-sanych/data/AudioSet/data'
    sample_rate: 16000
    fbank_bins: 128
    fbank_mean: 15.41663
    fbank_std: 13.11164
    wav_len: 158960

    train:
      target: specvqgan.data.audioset.AudioSetFbankTrain
      params:
        specs_dataset_cfg: /datablob/users/v-chengw/data/AudioSet/data/train.tsv
    validation:
      target: specvqgan.data.audioset.AudioSetFbankValidation
      params:
        specs_dataset_cfg: /datablob/users/v-chengw/data/AudioSet/data/valid.tsv
